# Generated by Django 5.0.6 on 2024-06-04 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_friendrequest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='accepted',
            new_name='is_accepted',
        ),
    ]
