# Generated by Django 5.0.6 on 2024-06-04 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_accepted_friendrequest_is_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendrequest',
            old_name='is_accepted',
            new_name='accepted',
        ),
    ]
